version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      egui:
        patterns: ["egui*", "eframe", "wgpu*"]
      rust-deps:
        patterns: ["*"]
        exclude-patterns: ["egui*", "eframe", "wgpu*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
