//! Parametric furniture catalog.
//!
//! Every item is generated by code at the exact size requested, so pieces are
//! always true to scale, need no asset files or licenses, and an AI agent only
//! has to say "`bed-double` at [x, y]". Each item provides a 3D mesh
//! ([`piece_mesh`]) and an architectural plan symbol ([`plan_symbol`]).

mod import;
mod mesh;
mod models;
mod symbols;

pub use import::{ImportError, ImportedModel, load_model};
pub use mesh::{Axis, Mesh, Rgb, rgb, shade};
use newera_core::{Furniture, Opening, OpeningKind};
pub use symbols::{SymbolShape, plan_symbol};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    Living,
    Dining,
    Kitchen,
    Bedroom,
    Bathroom,
    Laundry,
    Office,
    DoorsWindows,
    Structure,
    Decor,
    Outdoor,
}

impl Category {
    pub const ALL: [Self; 11] = [
        Self::Living,
        Self::Dining,
        Self::Kitchen,
        Self::Bedroom,
        Self::Bathroom,
        Self::Laundry,
        Self::Office,
        Self::DoorsWindows,
        Self::Structure,
        Self::Decor,
        Self::Outdoor,
    ];

    pub fn id(self) -> &'static str {
        match self {
            Self::Living => "living",
            Self::Dining => "dining",
            Self::Kitchen => "kitchen",
            Self::Bedroom => "bedroom",
            Self::Bathroom => "bathroom",
            Self::Laundry => "laundry",
            Self::Office => "office",
            Self::DoorsWindows => "doors-windows",
            Self::Structure => "structure",
            Self::Decor => "decor",
            Self::Outdoor => "outdoor",
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::Living => "Sala de estar",
            Self::Dining => "Sala de jantar",
            Self::Kitchen => "Cozinha",
            Self::Bedroom => "Quarto",
            Self::Bathroom => "Banheiro",
            Self::Laundry => "Lavanderia",
            Self::Office => "Escritório",
            Self::DoorsWindows => "Portas e janelas",
            Self::Structure => "Estrutura",
            Self::Decor => "Decoração",
            Self::Outdoor => "Área externa",
        }
    }
}

/// Which procedural generator builds an item, with its style parameters.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Model {
    Sofa { seats: u8 },
    Bed { pillows: u8 },
    Table { round: bool },
    Chair,
    Stool,
    OfficeChair,
    Cabinet { doors: u8, drawers: u8 },
    Shelf { levels: u8 },
    TvStand,
    Tv,
    Fridge,
    Stove,
    SinkCounter,
    Counter,
    WallCabinet,
    Appliance { round_door: bool },
    Microwave,
    Toilet,
    Basin,
    Shower,
    Bathtub,
    Door,
    Window { panes: u8 },
    Passage,
    Stairs { steps: u8 },
    Plant,
    Tree,
    Lamp,
    Rug,
    Car,
    Desk,
    Crib,
    Column { round: bool },
    Box,
}

/// Opening settings a catalog door or window starts with.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpeningPreset {
    pub kind: OpeningKind,
    pub leaves: u8,
    pub sliding: bool,
}

impl OpeningPreset {
    pub fn to_opening(self) -> Opening {
        Opening {
            kind: self.kind,
            leaves: self.leaves,
            sliding: self.sliding,
            ..Opening::default()
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CatalogItem {
    pub id: &'static str,
    pub name: &'static str,
    pub category: Category,
    /// Default width, depth, height in cm.
    pub size: [f64; 3],
    pub elevation: f64,
    pub color: [u8; 3],
    pub model: Model,
    pub opening: Option<OpeningPreset>,
    /// Extra search words (synonyms, English).
    pub keywords: &'static str,
}

const fn item(
    id: &'static str,
    name: &'static str,
    category: Category,
    size: [f64; 3],
    color: [u8; 3],
    model: Model,
    keywords: &'static str,
) -> CatalogItem {
    CatalogItem {
        id,
        name,
        category,
        size,
        elevation: 0.0,
        color,
        model,
        opening: None,
        keywords,
    }
}

const fn raised(mut item: CatalogItem, elevation: f64) -> CatalogItem {
    item.elevation = elevation;
    item
}

const fn opening(
    mut item: CatalogItem,
    kind: OpeningKind,
    leaves: u8,
    sliding: bool,
) -> CatalogItem {
    item.opening = Some(OpeningPreset {
        kind,
        leaves,
        sliding,
    });
    item
}

const FABRIC: [u8; 3] = [118, 128, 140];
const WOOD: [u8; 3] = [168, 124, 84];
const WHITE: [u8; 3] = [236, 236, 232];
const STEEL: [u8; 3] = [196, 199, 204];
const DARK: [u8; 3] = [52, 54, 60];

use Category as C;

pub static CATALOG: &[CatalogItem] = &[
    // Living room
    item(
        "sofa-3",
        "Sofá 3 lugares",
        C::Living,
        [210.0, 90.0, 85.0],
        FABRIC,
        Model::Sofa { seats: 3 },
        "sofa couch sofá",
    ),
    item(
        "sofa-2",
        "Sofá 2 lugares",
        C::Living,
        [160.0, 90.0, 85.0],
        FABRIC,
        Model::Sofa { seats: 2 },
        "sofa couch loveseat",
    ),
    item(
        "armchair",
        "Poltrona",
        C::Living,
        [85.0, 85.0, 85.0],
        [150, 110, 90],
        Model::Sofa { seats: 1 },
        "armchair poltrona cadeira",
    ),
    item(
        "coffee-table",
        "Mesa de centro",
        C::Living,
        [100.0, 60.0, 40.0],
        WOOD,
        Model::Table { round: false },
        "coffee table centro",
    ),
    item(
        "side-table",
        "Mesa lateral",
        C::Living,
        [50.0, 50.0, 55.0],
        WOOD,
        Model::Table { round: true },
        "side table apoio",
    ),
    item(
        "tv-stand",
        "Rack de TV",
        C::Living,
        [180.0, 45.0, 50.0],
        WOOD,
        Model::TvStand,
        "tv stand rack",
    ),
    raised(
        item(
            "tv",
            "Televisão 55\"",
            C::Living,
            [124.0, 8.0, 72.0],
            DARK,
            Model::Tv,
            "tv television tela",
        ),
        60.0,
    ),
    item(
        "bookcase",
        "Estante",
        C::Living,
        [90.0, 35.0, 200.0],
        WOOD,
        Model::Shelf { levels: 5 },
        "bookcase shelf estante livros",
    ),
    item(
        "rug",
        "Tapete",
        C::Living,
        [200.0, 140.0, 1.0],
        [190, 170, 140],
        Model::Rug,
        "rug carpet tapete",
    ),
    item(
        "floor-lamp",
        "Luminária de piso",
        C::Living,
        [40.0, 40.0, 165.0],
        [230, 220, 200],
        Model::Lamp,
        "lamp light abajur luminaria",
    ),
    // Dining
    item(
        "dining-table-4",
        "Mesa de jantar 4 lugares",
        C::Dining,
        [120.0, 80.0, 75.0],
        WOOD,
        Model::Table { round: false },
        "dining table mesa",
    ),
    item(
        "dining-table-6",
        "Mesa de jantar 6 lugares",
        C::Dining,
        [180.0, 90.0, 75.0],
        WOOD,
        Model::Table { round: false },
        "dining table mesa",
    ),
    item(
        "round-table",
        "Mesa redonda",
        C::Dining,
        [110.0, 110.0, 75.0],
        WOOD,
        Model::Table { round: true },
        "round table mesa",
    ),
    item(
        "chair",
        "Cadeira",
        C::Dining,
        [45.0, 50.0, 90.0],
        WOOD,
        Model::Chair,
        "chair cadeira",
    ),
    item(
        "sideboard",
        "Aparador",
        C::Dining,
        [160.0, 45.0, 80.0],
        WOOD,
        Model::Cabinet {
            doors: 4,
            drawers: 0,
        },
        "sideboard buffet aparador",
    ),
    // Kitchen
    item(
        "fridge",
        "Geladeira",
        C::Kitchen,
        [70.0, 72.0, 180.0],
        STEEL,
        Model::Fridge,
        "fridge refrigerator geladeira",
    ),
    item(
        "stove",
        "Fogão 4 bocas",
        C::Kitchen,
        [60.0, 62.0, 90.0],
        STEEL,
        Model::Stove,
        "stove cooker oven fogao",
    ),
    item(
        "sink-counter",
        "Bancada com pia",
        C::Kitchen,
        [120.0, 60.0, 90.0],
        WHITE,
        Model::SinkCounter,
        "sink counter pia cuba",
    ),
    item(
        "base-cabinet",
        "Armário de cozinha (baixo)",
        C::Kitchen,
        [60.0, 60.0, 90.0],
        WHITE,
        Model::Counter,
        "base cabinet balcao armario",
    ),
    raised(
        item(
            "wall-cabinet",
            "Armário aéreo",
            C::Kitchen,
            [60.0, 35.0, 70.0],
            WHITE,
            Model::WallCabinet,
            "wall cabinet aereo armario",
        ),
        150.0,
    ),
    item(
        "dishwasher",
        "Lava-louças",
        C::Kitchen,
        [60.0, 60.0, 85.0],
        STEEL,
        Model::Appliance { round_door: false },
        "dishwasher lava louças",
    ),
    raised(
        item(
            "microwave",
            "Micro-ondas",
            C::Kitchen,
            [50.0, 40.0, 30.0],
            DARK,
            Model::Microwave,
            "microwave micro ondas",
        ),
        90.0,
    ),
    item(
        "kitchen-island",
        "Ilha de cozinha",
        C::Kitchen,
        [180.0, 90.0, 90.0],
        WHITE,
        Model::Counter,
        "island ilha bancada",
    ),
    item(
        "stool",
        "Banqueta alta",
        C::Kitchen,
        [40.0, 40.0, 75.0],
        DARK,
        Model::Stool,
        "stool banqueta",
    ),
    // Bedroom
    item(
        "bed-double",
        "Cama de casal",
        C::Bedroom,
        [158.0, 208.0, 55.0],
        [214, 206, 190],
        Model::Bed { pillows: 2 },
        "double bed cama casal",
    ),
    item(
        "bed-queen",
        "Cama queen",
        C::Bedroom,
        [168.0, 208.0, 55.0],
        [214, 206, 190],
        Model::Bed { pillows: 2 },
        "queen bed cama",
    ),
    item(
        "bed-king",
        "Cama king",
        C::Bedroom,
        [203.0, 213.0, 55.0],
        [214, 206, 190],
        Model::Bed { pillows: 2 },
        "king bed cama",
    ),
    item(
        "bed-single",
        "Cama de solteiro",
        C::Bedroom,
        [98.0, 198.0, 50.0],
        [200, 212, 224],
        Model::Bed { pillows: 1 },
        "single bed cama solteiro",
    ),
    item(
        "nightstand",
        "Criado-mudo",
        C::Bedroom,
        [50.0, 40.0, 55.0],
        WOOD,
        Model::Cabinet {
            doors: 0,
            drawers: 2,
        },
        "nightstand bedside criado mudo",
    ),
    item(
        "wardrobe",
        "Guarda-roupa",
        C::Bedroom,
        [180.0, 60.0, 220.0],
        WHITE,
        Model::Cabinet {
            doors: 3,
            drawers: 0,
        },
        "wardrobe closet guarda roupa armario",
    ),
    item(
        "dresser",
        "Cômoda",
        C::Bedroom,
        [100.0, 50.0, 85.0],
        WOOD,
        Model::Cabinet {
            doors: 0,
            drawers: 4,
        },
        "dresser chest comoda gaveteiro",
    ),
    item(
        "crib",
        "Berço",
        C::Bedroom,
        [70.0, 130.0, 100.0],
        WHITE,
        Model::Crib,
        "crib baby berco",
    ),
    // Bathroom
    item(
        "toilet",
        "Vaso sanitário",
        C::Bathroom,
        [40.0, 68.0, 78.0],
        WHITE,
        Model::Toilet,
        "toilet wc vaso privada",
    ),
    item(
        "basin-cabinet",
        "Gabinete com lavatório",
        C::Bathroom,
        [80.0, 48.0, 85.0],
        WHITE,
        Model::Basin,
        "basin sink lavatorio pia gabinete",
    ),
    item(
        "shower",
        "Box de chuveiro",
        C::Bathroom,
        [90.0, 90.0, 200.0],
        [170, 205, 225],
        Model::Shower,
        "shower box chuveiro",
    ),
    item(
        "bathtub",
        "Banheira",
        C::Bathroom,
        [170.0, 75.0, 55.0],
        WHITE,
        Model::Bathtub,
        "bathtub banheira",
    ),
    // Laundry
    item(
        "washer",
        "Máquina de lavar",
        C::Laundry,
        [60.0, 65.0, 85.0],
        WHITE,
        Model::Appliance { round_door: true },
        "washing machine washer lavar roupa",
    ),
    item(
        "dryer",
        "Secadora",
        C::Laundry,
        [60.0, 65.0, 85.0],
        WHITE,
        Model::Appliance { round_door: true },
        "dryer secadora",
    ),
    item(
        "laundry-sink",
        "Tanque",
        C::Laundry,
        [60.0, 55.0, 85.0],
        WHITE,
        Model::SinkCounter,
        "laundry sink tanque",
    ),
    // Office
    item(
        "desk",
        "Escrivaninha",
        C::Office,
        [120.0, 60.0, 75.0],
        WOOD,
        Model::Desk,
        "desk escrivaninha mesa escritorio",
    ),
    item(
        "office-chair",
        "Cadeira de escritório",
        C::Office,
        [62.0, 62.0, 105.0],
        DARK,
        Model::OfficeChair,
        "office chair cadeira escritorio",
    ),
    // Doors and windows
    opening(
        item(
            "door",
            "Porta",
            C::DoorsWindows,
            [80.0, 15.0, 210.0],
            WOOD,
            Model::Door,
            "door porta",
        ),
        OpeningKind::Door,
        1,
        false,
    ),
    opening(
        item(
            "door-double",
            "Porta dupla",
            C::DoorsWindows,
            [140.0, 15.0, 210.0],
            WOOD,
            Model::Door,
            "double door porta dupla",
        ),
        OpeningKind::Door,
        2,
        false,
    ),
    opening(
        item(
            "door-sliding",
            "Porta de correr",
            C::DoorsWindows,
            [160.0, 15.0, 210.0],
            [220, 230, 235],
            Model::Door,
            "sliding door porta correr",
        ),
        OpeningKind::Door,
        2,
        true,
    ),
    opening(
        item(
            "passage",
            "Vão livre",
            C::DoorsWindows,
            [90.0, 15.0, 210.0],
            WHITE,
            Model::Passage,
            "passage opening vao passagem",
        ),
        OpeningKind::Passage,
        1,
        false,
    ),
    opening(
        raised(
            item(
                "window",
                "Janela",
                C::DoorsWindows,
                [120.0, 15.0, 110.0],
                WHITE,
                Model::Window { panes: 2 },
                "window janela",
            ),
            100.0,
        ),
        OpeningKind::Window,
        2,
        true,
    ),
    opening(
        raised(
            item(
                "window-small",
                "Janela basculante",
                C::DoorsWindows,
                [60.0, 15.0, 60.0],
                WHITE,
                Model::Window { panes: 1 },
                "small window basculante janela banheiro",
            ),
            150.0,
        ),
        OpeningKind::Window,
        1,
        true,
    ),
    opening(
        item(
            "french-window",
            "Porta-janela",
            C::DoorsWindows,
            [200.0, 15.0, 220.0],
            WHITE,
            Model::Window { panes: 4 },
            "french window porta janela sacada",
        ),
        OpeningKind::Window,
        2,
        true,
    ),
    // Structure
    item(
        "stairs",
        "Escada reta",
        C::Structure,
        [90.0, 300.0, 280.0],
        WOOD,
        Model::Stairs { steps: 16 },
        "stairs staircase escada",
    ),
    item(
        "column",
        "Pilar",
        C::Structure,
        [30.0, 30.0, 250.0],
        WHITE,
        Model::Column { round: false },
        "column pillar pilar coluna",
    ),
    item(
        "column-round",
        "Coluna redonda",
        C::Structure,
        [30.0, 30.0, 250.0],
        WHITE,
        Model::Column { round: true },
        "round column coluna",
    ),
    item(
        "box",
        "Caixa",
        C::Structure,
        [50.0, 50.0, 50.0],
        [200, 190, 170],
        Model::Box,
        "box caixa volume",
    ),
    // Decor and outdoor
    item(
        "plant",
        "Planta em vaso",
        C::Decor,
        [50.0, 50.0, 110.0],
        [70, 140, 80],
        Model::Plant,
        "plant vaso planta",
    ),
    item(
        "tree",
        "Árvore",
        C::Outdoor,
        [300.0, 300.0, 500.0],
        [80, 140, 70],
        Model::Tree,
        "tree arvore",
    ),
    item(
        "car",
        "Carro",
        C::Outdoor,
        [450.0, 180.0, 150.0],
        [70, 110, 170],
        Model::Car,
        "car automovel carro garagem",
    ),
];

pub fn find(id: &str) -> Option<&'static CatalogItem> {
    CATALOG.iter().find(|item| item.id == id)
}

/// Accent-insensitive search over ids, names and keywords. An empty query
/// returns everything in catalog order.
pub fn search(query: &str) -> Vec<&'static CatalogItem> {
    let words: Vec<String> = fold(query).split_whitespace().map(str::to_owned).collect();
    CATALOG
        .iter()
        .filter(|item| {
            let haystack = fold(&format!(
                "{} {} {} {}",
                item.id,
                item.name,
                item.keywords,
                item.category.name()
            ));
            words.iter().all(|w| haystack.contains(w.as_str()))
        })
        .collect()
}

fn fold(text: &str) -> String {
    text.to_lowercase()
        .chars()
        .map(|c| match c {
            'á' | 'à' | 'â' | 'ã' | 'ä' => 'a',
            'é' | 'ê' | 'è' => 'e',
            'í' | 'î' => 'i',
            'ó' | 'ô' | 'õ' | 'ö' => 'o',
            'ú' | 'ü' => 'u',
            'ç' => 'c',
            other => other,
        })
        .collect()
}

impl CatalogItem {
    /// A new piece of this item, at its default size, centered at `position`.
    pub fn instantiate(
        &self,
        id: newera_core::FurnitureId,
        position: newera_core::Point2,
    ) -> Furniture {
        Furniture {
            id,
            catalog: self.id.to_owned(),
            name: self.name.to_owned(),
            position,
            elevation: self.elevation,
            angle: 0.0,
            width: self.size[0],
            depth: self.size[1],
            height: self.size[2],
            mirrored: false,
            color: None,
            opening: self.opening.map(OpeningPreset::to_opening),
            model: None,
            visible: true,
            level: None,
            ..Default::default()
        }
    }
}

/// 3D mesh of a piece in its local frame (see [`mesh`] module docs), at its
/// exact size. Unknown catalog ids render as a plain box.
pub fn piece_mesh(piece: &Furniture) -> Mesh {
    let item = find(&piece.catalog);
    let model = item.map_or(Model::Box, |i| i.model);
    let color = piece
        .color
        .or(item.map(|i| i.color))
        .unwrap_or([200, 190, 170]);
    models::build(model, piece, rgb(color))
}

#[cfg(test)]
mod tests {
    use newera_core::{FurnitureId, Point2};

    use super::*;

    #[test]
    fn every_item_has_a_unique_id_and_sane_size() {
        let mut ids = std::collections::HashSet::new();
        for item in CATALOG {
            assert!(ids.insert(item.id), "duplicate id {}", item.id);
            assert!(item.size.iter().all(|v| *v > 0.0), "{}", item.id);
        }
        assert!(CATALOG.len() >= 50);
    }

    #[test]
    fn every_mesh_fits_its_box_exactly_and_faces_outward() {
        for item in CATALOG {
            for size in [
                item.size,
                [item.size[0] * 1.3, item.size[1] * 0.8, item.size[2] * 1.1],
            ] {
                let mut piece = item.instantiate(FurnitureId(1), Point2::new(0.0, 0.0));
                (piece.width, piece.depth, piece.height) = (size[0], size[1], size[2]);
                let mesh = piece_mesh(&piece);
                assert!(!mesh.indices.is_empty(), "{} has no geometry", item.id);
                assert!(
                    mesh.indices
                        .iter()
                        .all(|i| (*i as usize) < mesh.positions.len())
                );
                let (min, max) = mesh.bounds().unwrap();
                #[allow(clippy::cast_possible_truncation)]
                let (w, h, d) = (size[0] as f32, size[2] as f32, size[1] as f32);
                let tol = 0.05;
                assert!(
                    (max[0] - min[0] - w).abs() < tol,
                    "{} width {} vs {w}",
                    item.id,
                    max[0] - min[0]
                );
                assert!(
                    (max[1] - min[1] - h).abs() < tol,
                    "{} height {} vs {h}",
                    item.id,
                    max[1] - min[1]
                );
                assert!(
                    (max[2] - min[2] - d).abs() < tol,
                    "{} depth {} vs {d}",
                    item.id,
                    max[2] - min[2]
                );
                assert!(min[1].abs() < tol, "{} rests on the floor", item.id);
                mesh::tests::assert_outward(&mesh);
            }
        }
    }

    #[test]
    fn search_is_accent_insensitive_and_bilingual() {
        let ids = |q: &str| search(q).iter().map(|i| i.id).collect::<Vec<_>>();
        assert!(ids("sofa").contains(&"sofa-3"));
        assert!(ids("Sofá 2").contains(&"sofa-2"));
        assert_eq!(ids("geladeira"), ["fridge"]);
        assert!(ids("cama casal").contains(&"bed-double"));
        assert!(ids("window").contains(&"window"));
        assert_eq!(search("").len(), CATALOG.len());
    }
}
