#!/usr/bin/env bash
# Installs 3D New Era AI on a Mac, for your user only (no sudo).
#
#   curl -fsSL https://raw.githubusercontent.com/leandrodaf/3d-new-era-ai/main/scripts/install-macos.sh | bash
#   ... | bash -s -- --uninstall
#
# By default it downloads the app from the latest release (Apple Silicon or
# Intel) — seconds, no compiler. Files fetched with curl carry no quarantine
# flag, so Gatekeeper opens the app without the "unidentified developer" wall.
# When there is no build for this Mac, or with NEWERA_REF=<branch|tag|commit>,
# it builds from source instead.
#
#   - Already up to date? Nothing is downloaded (the commit is compared first).
#   - Building: Rust already installed (rustup or Homebrew, 1.95+) is used as
#     it is; otherwise a private Rust goes into the temporary folder and leaves
#     with it. Run from inside a clone, that source is used untouched.
#   - At the end — success or failure — the temporary folder is deleted. What
#     stays: the app in ~/Applications and the `newera` link in ~/.local/bin.
#
# Environment: NEWERA_REF (build this branch, tag or commit from source),
# NEWERA_APPS (default ~/Applications), NEWERA_FORCE=1 to reinstall anyway.
set -euo pipefail

OWNER_REPO="leandrodaf/3d-new-era-ai"
NEWERA_APPS="${NEWERA_APPS:-$HOME/Applications}"
APP="$NEWERA_APPS/3D New Era AI.app"
BIN_DIR="$HOME/.local/bin"
# Which release or commit is installed, kept outside the signed app.
STATE="$HOME/Library/Application Support/3D New Era AI/installed"
MIN_RUST="1.95"

# Portuguese for a pt system, English for everyone else. The Terminal often
# leaves LANG empty on a Mac, so fall back to what macOS itself is set to.
case "${NEWERA_LANG:-${LC_ALL:-${LC_MESSAGES:-${LANG:-}}}}" in
    pt*) PT=1 ;;
    ?*) PT=0 ;;
    *) case "$(defaults read -g AppleLocale 2>/dev/null || true)" in
           pt*) PT=1 ;;
           *) PT=0 ;;
       esac ;;
esac
t() { [ "$PT" = 1 ] && printf '%s' "$1" || printf '%s' "$2"; }

step() { printf '\n\033[1;34m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
fail() { printf '\n\033[1;31m%s:\033[0m %s\n' "$(t erro error)" "$*" >&2; exit 1; }

# --- logo begin (generated by scripts/make-icons.py) ---
logo() {
    [ -t 1 ] && [ -z "${NO_COLOR:-}" ] || return 0
    printf '%b\n' '' \
'  \033[49m     \033[38;2;21;21;19m▄\033[38;2;23;22;19m▄\033[38;2;22;21;19m▄▄▄▄▄▄▄▄▄▄▄▄▄▄\033[38;2;23;22;19m▄\033[38;2;21;21;19m▄     \033[0m' \
'  \033[49m  \033[38;2;23;22;19m▄\033[48;2;22;21;19m▀\033[38;2;22;21;19m▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀\033[38;2;23;22;19m▀\033[49m▄  \033[0m' \
'  \033[49m \033[38;2;21;21;19m▄\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀\033[48;2;25;24;22m▀\033[48;2;47;46;44m▀\033[48;2;47;45;43m▀▀▀▀▀▀▀▀▀▀▀▀▀▀\033[48;2;47;46;44m▀\033[48;2;25;24;22m▀\033[48;2;22;21;19m▀▀▀\033[38;2;21;21;19m\033[49m▄ \033[0m' \
'  \033[49m \033[38;2;23;22;19m\033[48;2;22;21;19m▀\033[38;2;22;21;19m▀▀▀\033[38;2;47;46;44m\033[48;2;47;45;43m▀\033[38;2;247;246;239m\033[48;2;246;243;237m▀\033[38;2;245;243;237m\033[48;2;174;173;167m▀\033[38;2;245;243;236m\033[48;2;120;118;114m▀▀▀▀▀▀▀▀▀▀\033[48;2;128;128;133m▀\033[38;2;245;243;237m\033[48;2;161;169;206m▀\033[38;2;246;244;237m\033[48;2;207;211;240m▀\033[38;2;247;246;239m\033[48;2;246;244;237m▀\033[38;2;47;46;44m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀\033[38;2;23;22;19m▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀▀▀▀\033[48;2;27;28;31m▀\033[38;2;25;25;26m\033[48;2;104;121;201m▀\033[38;2;79;91;147m\033[48;2;125;147;255m▀\033[38;2;123;145;247m\033[48;2;89;103;168m▀\033[38;2;126;148;254m\033[48;2;43;46;64m▀\033[38;2;176;187;243m\033[48;2;121;119;115m▀\033[38;2;246;243;237m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀▀▀\033[38;2;22;21;18m\033[48;2;51;56;83m▀\033[38;2;93;108;177m\033[48;2;126;148;254m▀\033[38;2;124;146;251m\033[48;2;73;83;133m▀\033[38;2;59;66;100m\033[48;2;22;21;19m▀\033[38;2;22;21;19m▀▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;120;118;114m\033[48;2;121;120;116m▀\033[38;2;22;21;19m\033[48;2;25;24;22m▀▀▀▀▀\033[48;2;24;23;20m▀\033[38;2;92;106;177m\033[48;2;120;139;235m▀\033[38;2;119;139;237m\033[48;2;88;102;165m▀\033[38;2;25;24;25m\033[48;2;23;22;20m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;246;244;237m\033[48;2;246;244;237m▀\033[38;2;243;240;233m\033[48;2;182;180;174m▀\033[38;2;241;238;231m\033[48;2;133;131;127m▀▀▀▀▀\033[48;2;135;133;128m▀\033[38;2;242;240;235m\033[48;2;243;240;233m▀\033[38;2;134;132;130m\033[48;2;133;131;127m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀▀\033[38;2;25;24;22m\033[48;2;25;24;22m▀\033[38;2;241;238;231m\033[48;2;241;238;231m▀\033[38;2;133;131;127m\033[48;2;133;131;127m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀▀\033[38;2;25;24;22m\033[48;2;25;24;22m▀\033[38;2;241;238;231m\033[48;2;241;238;231m▀\033[38;2;133;131;127m\033[48;2;133;131;127m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[38;2;120;118;114m\033[48;2;120;118;114m▀\033[38;2;245;243;236m\033[48;2;245;243;236m▀\033[38;2;47;45;43m\033[48;2;47;45;43m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀▀\033[49m \033[0m' \
'  \033[49m \033[38;2;22;21;19m\033[48;2;23;22;19m▀\033[48;2;22;21;19m▀▀▀\033[38;2;47;45;43m\033[48;2;47;46;44m▀\033[38;2;246;243;237m\033[48;2;247;246;239m▀\033[38;2;174;173;167m\033[48;2;245;243;237m▀\033[38;2;120;118;114m\033[48;2;245;243;236m▀▀▀▀▀\033[38;2;121;120;116m▀\033[38;2;242;239;232m\033[48;2;246;244;237m▀\033[38;2;182;180;174m\033[48;2;246;243;237m▀\033[38;2;120;118;114m\033[48;2;245;243;236m▀▀▀▀\033[38;2;174;173;167m\033[48;2;245;243;237m▀\033[38;2;246;243;237m\033[48;2;247;246;239m▀\033[38;2;47;45;43m\033[48;2;47;46;44m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀\033[48;2;23;22;19m▀\033[49m \033[0m' \
'  \033[49m \033[38;2;21;21;19m▀\033[38;2;22;21;19m\033[48;2;22;21;19m▀▀▀\033[38;2;25;24;22m▀\033[38;2;47;46;44m▀\033[38;2;47;45;43m▀▀▀▀▀▀▀▀▀▀▀▀▀▀\033[38;2;47;46;44m▀\033[38;2;25;24;22m▀\033[38;2;22;21;19m▀▀▀\033[38;2;21;21;19m\033[49m▀ \033[0m' \
'  \033[49m  \033[38;2;23;22;19m▀\033[38;2;22;21;19m\033[48;2;23;22;19m▀\033[48;2;22;21;19m▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀\033[48;2;23;22;19m▀\033[38;2;23;22;19m\033[49m▀  \033[0m' \
'  \033[49m     \033[38;2;21;21;19m▀\033[38;2;23;22;19m▀\033[38;2;22;21;19m▀▀▀▀▀▀▀▀▀▀▀▀▀▀\033[38;2;23;22;19m▀\033[38;2;21;21;19m▀     \033[0m' ''
}
# --- logo end ---

[ "$(uname -s)" = "Darwin" ] || fail "$(t 'este script é para macOS (no Linux/Windows veja o README).' 'this script is for macOS (see the README for Linux/Windows).')"
[ "$(id -u)" -ne 0 ] || fail "$(t 'não rode como root/sudo: tudo é instalado só para o seu usuário.' 'do not run as root/sudo: everything is installed for your user only.')"

if [ "${1:-}" = "--uninstall" ]; then
    step "$(t Desinstalando Uninstalling)"
    rm -rf "$APP"
    rm -f "$STATE"
    [ -L "$BIN_DIR/newera" ] && rm -f "$BIN_DIR/newera"
    if command -v claude >/dev/null 2>&1 && claude mcp get newera >/dev/null 2>&1; then
        claude mcp remove --scope user newera >/dev/null 2>&1 || true
    fi
    if command -v codex >/dev/null 2>&1 && codex mcp get newera >/dev/null 2>&1; then
        codex mcp remove newera >/dev/null 2>&1 || true
    fi
    info "$(t "removidos: $APP, $BIN_DIR/newera e o MCP 'newera' do Claude Code e do Codex" \
             "removed: $APP, $BIN_DIR/newera and the 'newera' MCP from Claude Code and Codex")"
    exit 0
fi

logo

command -v curl >/dev/null 2>&1 || fail "$(t 'curl não encontrado.' 'curl not found.')"

# Everything temporary lives here and is deleted on any exit.
WORK=$(mktemp -d "${TMPDIR:-/tmp}/newera-install.XXXXXX")
cleanup() {
    # Build files can be read-only (cargo registry): make them removable first.
    chmod -R u+w "$WORK" 2>/dev/null || true
    rm -rf "$WORK"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

version_ge() { # version_ge 1.96.0 1.95 -> true
    [ "$(printf '%s\n%s\n' "$2" "$1" | sort -t. -k1,1n -k2,2n -k3,3n | head -1)" = "$2" ]
}

github_sha() { # github_sha <ref> -> commit sha
    curl -fsSL -H "Accept: application/vnd.github.sha" \
        "https://api.github.com/repos/$OWNER_REPO/commits/$1"
}

installed_commit() { cat "$STATE" 2>/dev/null || true; }
remember() { mkdir -p "$(dirname "$STATE")" && echo "$1" > "$STATE"; }

up_to_date() { # up_to_date <commit>
    [ "${NEWERA_FORCE:-0}" != "1" ] && [ "$1" != "local" ] \
        && [ "$(installed_commit)" = "$1" ] && [ -x "$APP/Contents/MacOS/newera" ]
}

place_app() { # place_app <built .app>: swap in the new app only once it is complete
    mkdir -p "$NEWERA_APPS"
    rm -rf "$APP"
    mv "$1" "$APP"
    # Tell Launch Services about the new bundle right away, so the Dock, Finder
    # and the .newera file icon update without a logout.
    local lsregister="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
    [ -x "$lsregister" ] && "$lsregister" -f "$APP" >/dev/null 2>&1 || true
    touch "$APP" 2>/dev/null || true
}

local_source() {
    for dir in "$PWD" "$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." 2>/dev/null && pwd || true)"; do
        if [ -n "$dir" ] && [ -f "$dir/crates/newera/Cargo.toml" ]; then
            echo "$dir"
            return
        fi
    done
}

# Returns 0 when the release app was installed (or already was), 1 to build instead.
install_release() {
    case "$(uname -m)" in
        arm64) ASSET="newera-macos-apple-silicon.zip" ;;
        x86_64) ASSET="newera-macos-intel.zip" ;;
        *) return 1 ;;
    esac
    step "$(t 'Última versão' 'Latest version')"
    # github.com/<repo>/releases/latest redirects to the newest tag. Unlike the
    # REST API it has no per-IP limit, so offices behind one IP aren't blocked.
    local location
    location=$(curl -fsSI -o /dev/null -w '%{redirect_url}' "https://github.com/$OWNER_REPO/releases/latest" 2>/dev/null || true)
    case "$location" in
        */releases/tag/*) TAG="${location##*/releases/tag/}" ;;
        *) info "$(t 'nenhuma release publicada ainda' 'no release published yet')"; return 1 ;;
    esac
    info "$TAG"
    if up_to_date "release:$TAG"; then
        info "$(t 'já instalado nesta versão: nada a baixar (NEWERA_FORCE=1 reinstala)' \
                 'already on this version: nothing to download (NEWERA_FORCE=1 reinstalls)')"
        return 0
    fi

    step "$(t Baixando Downloading) $ASSET"
    curl -fL --progress-bar -o "$WORK/app.zip" \
        "https://github.com/$OWNER_REPO/releases/download/$TAG/$ASSET" \
        || { info "$(t 'sem build pronto para este Mac nesta versão' 'no build for this Mac in this version')"; return 1; }
    mkdir -p "$WORK/unzip"
    ditto -x -k "$WORK/app.zip" "$WORK/unzip"
    local built="$WORK/unzip/3D New Era AI.app"
    "$built/Contents/MacOS/newera" --version >/dev/null 2>&1 \
        || { info "$(t 'o app baixado não abriu neste Mac' 'the downloaded app did not run on this Mac')"; return 1; }
    place_app "$built"
    remember "release:$TAG"
    info "ok: $("$APP/Contents/MacOS/newera" --version)"
}

build_from_source() {
    step "$(t 'Ferramentas do sistema' 'System tools')"
    # The compiler and linker come from Apple's Command Line Tools. Installing
    # them asks for an administrator password, so the script never does it.
    if ! xcode-select -p >/dev/null 2>&1 || ! xcrun --find cc >/dev/null 2>&1; then
        fail "$(t 'para compilar faltam as Xcode Command Line Tools (compilador da Apple).
       Instale uma vez com:  xcode-select --install
       e rode este script de novo.' 'building needs the Xcode Command Line Tools (Apple\'s compiler).
       Install them once with:  xcode-select --install
       then run this script again.')"
    fi
    info "Command Line Tools: $(xcode-select -p)"

    step "$(t 'Código-fonte' 'Source code')"
    local src ref="${NEWERA_REF:-main}"
    src=$(local_source)
    if [ -n "$src" ]; then
        COMMIT=$(git -C "$src" rev-parse HEAD 2>/dev/null || echo "local")
        info "$(t "usando o clone em $src ($COMMIT) — nada a baixar" \
                 "using the clone at $src ($COMMIT) — nothing to download")"
    else
        if COMMIT=$(github_sha "$ref" 2>/dev/null) && [ -n "$COMMIT" ]; then
            info "$(t "$ref está em ${COMMIT:0:12}" "$ref is at ${COMMIT:0:12}")"
        else
            # API unavailable (rate limit): build the ref as named, without the up-to-date check.
            COMMIT="$ref"
            info "$(t "$ref (não consegui ver o commit; compilando mesmo assim)" \
                     "$ref (could not read the commit; building anyway)")"
        fi
    fi
    if up_to_date "$COMMIT"; then
        info "$(t 'já instalado nesta versão: nada a baixar nem compilar (NEWERA_FORCE=1 recompila)' \
                 'already on this version: nothing to download or build (NEWERA_FORCE=1 rebuilds)')"
        return
    fi
    if [ -z "$src" ]; then
        src="$WORK/src"
        mkdir -p "$src"
        curl -fsSL "https://codeload.github.com/$OWNER_REPO/tar.gz/$COMMIT" \
            | tar -xz -C "$src" --strip-components 1
        info "$(t 'baixado para a pasta temporária' 'downloaded into the temporary folder')"
    fi

    step "Rust"
    # Use the Rust already on the machine when it is new enough; pinning the
    # toolchain keeps rustup from fetching extra components the repo lists.
    # shellcheck disable=SC1091
    [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
    local rust_ok=0 have toolchain
    if command -v rustc >/dev/null 2>&1 && command -v cargo >/dev/null 2>&1; then
        if command -v rustup >/dev/null 2>&1; then
            toolchain=$( (cd "$HOME" && rustup show active-toolchain 2>/dev/null) | awk '{print $1}')
            [ -n "$toolchain" ] && export RUSTUP_TOOLCHAIN="$toolchain"
        fi
        have=$(rustc --version 2>/dev/null | awk '{print $2}')
        if [ -n "$have" ] && version_ge "$have" "$MIN_RUST"; then
            rust_ok=1
            info "$(t 'usando o Rust já instalado' 'using the Rust already installed'): $have${RUSTUP_TOOLCHAIN:+ ($RUSTUP_TOOLCHAIN)}"
        else
            info "$(t "Rust ${have:-?} é anterior ao $MIN_RUST exigido; não vou mexer nele" \
                     "Rust ${have:-?} is older than the $MIN_RUST required; leaving it alone")"
            unset RUSTUP_TOOLCHAIN
        fi
    fi
    if [ "$rust_ok" = 0 ]; then
        # Private, temporary Rust: never touches ~/.cargo, ~/.rustup or the shell profile.
        export RUSTUP_HOME="$WORK/rustup" CARGO_HOME="$WORK/cargo"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
            | sh -s -- -y --profile minimal --default-toolchain stable --no-modify-path >/dev/null
        export PATH="$CARGO_HOME/bin:$PATH" RUSTUP_TOOLCHAIN=stable
        info "$(t 'Rust temporário' 'Temporary Rust'): $(rustc --version) $(t '(apagado no final)' '(deleted at the end)')"
    fi

    step "$(t 'Compilando (a primeira vez leva alguns minutos)' 'Building (the first time takes a few minutes)')"
    # Half the cores keeps the Mac usable and cool while it builds.
    local jobs=$(($(sysctl -n hw.ncpu) / 2))
    [ "$jobs" -ge 1 ] || jobs=1
    # Build output goes to the temporary folder, even for a local clone.
    export CARGO_TARGET_DIR="$WORK/target"
    (cd "$src" && cargo build -p newera --release --locked -j "$jobs")
    [ -x "$CARGO_TARGET_DIR/release/newera" ] || fail "$(t 'o build terminou sem gerar o binário.' 'the build finished without producing the binary.')"

    step "$(t Aplicativo Application)"
    mkdir -p "$WORK/app"
    bash "$src/scripts/macos-app.sh" "$CARGO_TARGET_DIR/release/newera" "$WORK/app" "$COMMIT" >/dev/null
    place_app "$WORK/app/3D New Era AI.app"
    [[ "$COMMIT" =~ ^[0-9a-f]{40}$ ]] && remember "$COMMIT"
    info "ok (${COMMIT:0:12})"
}

if [ -n "${NEWERA_REF:-}" ] || [ -n "$(local_source)" ] || ! install_release; then
    build_from_source
fi
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true

step "$(t 'Comando newera em' 'The newera command in') $BIN_DIR"
mkdir -p "$BIN_DIR"
ln -sfn "$APP/Contents/MacOS/newera" "$BIN_DIR/newera"
case ":$PATH:" in
    *":$BIN_DIR:"*) info "ok" ;;
    *)
        PROFILE="$HOME/.zprofile"
        [ "${SHELL##*/}" = "bash" ] && PROFILE="$HOME/.bash_profile"
        if ! grep -qs 'newera: ~/.local/bin' "$PROFILE"; then
            printf '\n# newera: ~/.local/bin\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$PROFILE"
        fi
        info "$(t "adicionado ao PATH em $PROFILE (abra um terminal novo)" \
                 "added to PATH in $PROFILE (open a new terminal)")"
        ;;
esac

MCP_URL="http://127.0.0.1:7878/mcp"
if command -v claude >/dev/null 2>&1; then
    step "$(t 'MCP no Claude Code' 'MCP in Claude Code')"
    if claude mcp get newera >/dev/null 2>&1; then
        info "$(t 'já registrado' 'already registered')"
    elif claude mcp add --scope user --transport http newera "$MCP_URL" >/dev/null 2>&1; then
        info "$(t "servidor 'newera' registrado" "'newera' server registered")"
    else
        info "$(t 'não consegui registrar; rode' 'could not register; run'): claude mcp add --transport http newera $MCP_URL"
    fi
fi
if command -v codex >/dev/null 2>&1; then
    step "$(t 'MCP no Codex' 'MCP in Codex')"
    if codex mcp get newera >/dev/null 2>&1; then
        info "$(t 'já registrado' 'already registered')"
    elif codex mcp add newera --url "$MCP_URL" >/dev/null 2>&1; then
        info "$(t "servidor 'newera' registrado" "'newera' server registered")"
    else
        info "$(t 'não consegui registrar; rode' 'could not register; run'): codex mcp add newera --url $MCP_URL"
    fi
fi

printf '\n\033[1;32m%s\033[0m %s\n' "$(t 'Pronto!' 'Done!')" \
    "$(t '(arquivos temporários apagados ao sair)' '(temporary files deleted on exit)')"
if [ "$PT" = 1 ]; then
cat <<DONE
  Abrir:        open "$APP"   (ou Spotlight: "3D New Era AI")
  Terminal:     newera --demo
  Sem janela:   newera serve
  MCP:          http://127.0.0.1:7878/mcp (com o editor aberto; outras IAs: veja o README)
  Atualizar:    rode o mesmo comando de novo
  Desinstalar:  rode com --uninstall
DONE
else
cat <<DONE
  Open:         open "$APP"   (or Spotlight: "3D New Era AI")
  Terminal:     newera --demo
  Headless:     newera serve
  MCP:          http://127.0.0.1:7878/mcp (with the editor open; other AIs: see the README)
  Update:       run the same command again
  Uninstall:    run it with --uninstall
DONE
fi
