# Installs 3D New Era AI on Windows, for your user only (no administrator).
#
#   irm https://raw.githubusercontent.com/leandrodaf/3d-new-era-ai/main/scripts/install-windows.ps1 | iex
#
# Downloads the latest release into %LOCALAPPDATA%\Programs\3D New Era AI,
# adds Start menu and desktop shortcuts, puts `newera` on your user PATH,
# registers an uninstaller in Settings > Apps and the MCP server in Claude
# Code when it is installed. Files fetched this way carry no "downloaded from
# the internet" mark, so SmartScreen doesn't stop the app. Running it again
# updates; nothing is downloaded when you already have the latest version.
# Temporary files are deleted at the end, success or failure.
#
# Uninstall: Settings > Apps > 3D New Era AI, or
#   & ([scriptblock]::Create((irm https://raw.githubusercontent.com/leandrodaf/3d-new-era-ai/main/scripts/install-windows.ps1))) -Uninstall

param([switch]$Uninstall, [switch]$Force)

# The language Windows is set to, of the four the app speaks; English for
# every other one ($env:NEWERA_LANG forces one).
function Get-LangTag($name, $fallback) {
    switch -Wildcard ($name) { 'pt*' { 'pt' } 'es*' { 'es' } 'fr*' { 'fr' } default { $fallback } }
}
$script:Lang =
    if ($env:NEWERA_LANG) { Get-LangTag $env:NEWERA_LANG 'en' }
    else {
        $ui = Get-LangTag (Get-UICulture).Name ''
        if ($ui) { $ui } else { Get-LangTag (Get-Culture).Name 'en' }
    }
function T($pt, $en, $es, $fr) {
    switch ($script:Lang) { 'pt' { $pt } 'es' { $es } 'fr' { $fr } default { $en } }
}

# --- logo begin (generated by scripts/make-icons.py) ---
function Show-Logo {
    if ($env:NO_COLOR) { return }
    $vt = $Host.UI.PSObject.Properties['SupportsVirtualTerminal']
    if ($vt -and -not $vt.Value) { return }
    $e = [char]27; $b = [char]0x2580; $d = [char]0x2584
    Write-Host ''
    Write-Host "  $($e)[49m     $($e)[38;2;21;21;19m$($d)$($e)[38;2;23;22;19m$($d)$($e)[38;2;22;21;19m$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($d)$($e)[38;2;23;22;19m$($d)$($e)[38;2;21;21;19m$($d)     $($e)[0m"
    Write-Host "  $($e)[49m  $($e)[38;2;23;22;19m$($d)$($e)[48;2;22;21;19m$($b)$($e)[38;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[38;2;23;22;19m$($b)$($e)[49m$($d)  $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;21;21;19m$($d)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[48;2;25;24;22m$($b)$($e)[48;2;47;46;44m$($b)$($e)[48;2;47;45;43m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[48;2;47;46;44m$($b)$($e)[48;2;25;24;22m$($b)$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;21;21;19m$($e)[49m$($d) $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;23;22;19m$($e)[48;2;22;21;19m$($b)$($e)[38;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;47;46;44m$($e)[48;2;47;45;43m$($b)$($e)[38;2;247;246;239m$($e)[48;2;246;243;237m$($b)$($e)[38;2;245;243;237m$($e)[48;2;174;173;167m$($b)$($e)[38;2;245;243;236m$($e)[48;2;120;118;114m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[48;2;128;128;133m$($b)$($e)[38;2;245;243;237m$($e)[48;2;161;169;206m$($b)$($e)[38;2;246;244;237m$($e)[48;2;207;211;240m$($b)$($e)[38;2;247;246;239m$($e)[48;2;246;244;237m$($b)$($e)[38;2;47;46;44m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;23;22;19m$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[48;2;27;28;31m$($b)$($e)[38;2;25;25;26m$($e)[48;2;104;121;201m$($b)$($e)[38;2;79;91;147m$($e)[48;2;125;147;255m$($b)$($e)[38;2;123;145;247m$($e)[48;2;89;103;168m$($b)$($e)[38;2;126;148;254m$($e)[48;2;43;46;64m$($b)$($e)[38;2;176;187;243m$($e)[48;2;121;119;115m$($b)$($e)[38;2;246;243;237m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($b)$($e)[38;2;22;21;18m$($e)[48;2;51;56;83m$($b)$($e)[38;2;93;108;177m$($e)[48;2;126;148;254m$($b)$($e)[38;2;124;146;251m$($e)[48;2;73;83;133m$($b)$($e)[38;2;59;66;100m$($e)[48;2;22;21;19m$($b)$($e)[38;2;22;21;19m$($b)$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;120;118;114m$($e)[48;2;121;120;116m$($b)$($e)[38;2;22;21;19m$($e)[48;2;25;24;22m$($b)$($b)$($b)$($b)$($b)$($e)[48;2;24;23;20m$($b)$($e)[38;2;92;106;177m$($e)[48;2;120;139;235m$($b)$($e)[38;2;119;139;237m$($e)[48;2;88;102;165m$($b)$($e)[38;2;25;24;25m$($e)[48;2;23;22;20m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;246;244;237m$($e)[48;2;246;244;237m$($b)$($e)[38;2;243;240;233m$($e)[48;2;182;180;174m$($b)$($e)[38;2;241;238;231m$($e)[48;2;133;131;127m$($b)$($b)$($b)$($b)$($b)$($e)[48;2;135;133;128m$($b)$($e)[38;2;242;240;235m$($e)[48;2;243;240;233m$($b)$($e)[38;2;134;132;130m$($e)[48;2;133;131;127m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($e)[38;2;25;24;22m$($e)[48;2;25;24;22m$($b)$($e)[38;2;241;238;231m$($e)[48;2;241;238;231m$($b)$($e)[38;2;133;131;127m$($e)[48;2;133;131;127m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($e)[38;2;25;24;22m$($e)[48;2;25;24;22m$($b)$($e)[38;2;241;238;231m$($e)[48;2;241;238;231m$($b)$($e)[38;2;133;131;127m$($e)[48;2;133;131;127m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[38;2;120;118;114m$($e)[48;2;120;118;114m$($b)$($e)[38;2;245;243;236m$($e)[48;2;245;243;236m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;45;43m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;22;21;19m$($e)[48;2;23;22;19m$($b)$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;46;44m$($b)$($e)[38;2;246;243;237m$($e)[48;2;247;246;239m$($b)$($e)[38;2;174;173;167m$($e)[48;2;245;243;237m$($b)$($e)[38;2;120;118;114m$($e)[48;2;245;243;236m$($b)$($b)$($b)$($b)$($b)$($e)[38;2;121;120;116m$($b)$($e)[38;2;242;239;232m$($e)[48;2;246;244;237m$($b)$($e)[38;2;182;180;174m$($e)[48;2;246;243;237m$($b)$($e)[38;2;120;118;114m$($e)[48;2;245;243;236m$($b)$($b)$($b)$($b)$($e)[38;2;174;173;167m$($e)[48;2;245;243;237m$($b)$($e)[38;2;246;243;237m$($e)[48;2;247;246;239m$($b)$($e)[38;2;47;45;43m$($e)[48;2;47;46;44m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[48;2;23;22;19m$($b)$($e)[49m $($e)[0m"
    Write-Host "  $($e)[49m $($e)[38;2;21;21;19m$($b)$($e)[38;2;22;21;19m$($e)[48;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;25;24;22m$($b)$($e)[38;2;47;46;44m$($b)$($e)[38;2;47;45;43m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[38;2;47;46;44m$($b)$($e)[38;2;25;24;22m$($b)$($e)[38;2;22;21;19m$($b)$($b)$($b)$($e)[38;2;21;21;19m$($e)[49m$($b) $($e)[0m"
    Write-Host "  $($e)[49m  $($e)[38;2;23;22;19m$($b)$($e)[38;2;22;21;19m$($e)[48;2;23;22;19m$($b)$($e)[48;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[48;2;23;22;19m$($b)$($e)[38;2;23;22;19m$($e)[49m$($b)  $($e)[0m"
    Write-Host "  $($e)[49m     $($e)[38;2;21;21;19m$($b)$($e)[38;2;23;22;19m$($b)$($e)[38;2;22;21;19m$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($b)$($e)[38;2;23;22;19m$($b)$($e)[38;2;21;21;19m$($b)     $($e)[0m"
    Write-Host ''
}
# --- logo end ---

function Install-NewEra {
    param([switch]$Uninstall, [switch]$Force)
    $ErrorActionPreference = 'Stop'
    $ProgressPreference = 'SilentlyContinue'  # Invoke-WebRequest is much faster without it
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $repo = 'leandrodaf/3d-new-era-ai'
    $name = '3D New Era AI'
    $dir = Join-Path $env:LOCALAPPDATA "Programs\$name"
    $startMenu = Join-Path ([Environment]::GetFolderPath('Programs')) "$name.lnk"
    $desktop = Join-Path ([Environment]::GetFolderPath('Desktop')) "$name.lnk"
    $uninstallKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\NewEraAI'
    $progId = 'NewEraAI.Project'

    function Step($text) { Write-Host "`n==> $text" -ForegroundColor Cyan }
    function Info($text) { Write-Host "    $text" }

    function Refresh-Shell {
        # Explorer caches icons and associations; this makes it re-read them.
        if (-not ('Win32.Shell' -as [type])) {
            Add-Type -Namespace Win32 -Name Shell -MemberDefinition @'
[DllImport("shell32.dll")] public static extern void SHChangeNotify(int eventId, uint flags, IntPtr item1, IntPtr item2);
'@
        }
        [Win32.Shell]::SHChangeNotify(0x08000000, 0x0000, [IntPtr]::Zero, [IntPtr]::Zero)
    }

    function Remove-FromUserPath($folder) {
        $path = [Environment]::GetEnvironmentVariable('Path', 'User')
        if ($path) {
            $kept = ($path -split ';') | Where-Object { $_ -and ($_.TrimEnd('\') -ne $folder.TrimEnd('\')) }
            [Environment]::SetEnvironmentVariable('Path', ($kept -join ';'), 'User')
        }
    }

    if (Get-Process -Name 'newera-gui', 'newera' -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -and $_.Path.StartsWith($dir, [StringComparison]::OrdinalIgnoreCase) }) {
        throw (T 'Feche o 3D New Era AI antes de continuar.' 'Close 3D New Era AI before continuing.' `
                 'Cierre 3D New Era AI antes de continuar.' "Fermez 3D New Era AI avant de continuer.")
    }

    if ($Uninstall) {
        Step (T 'Desinstalando' 'Uninstalling' 'Desinstalando' 'Désinstallation')
        Remove-Item -Recurse -Force $dir, $startMenu, $desktop -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force $uninstallKey -ErrorAction SilentlyContinue
        $classes = 'HKCU:\Software\Classes'
        if ((Get-ItemProperty -Path "$classes\.newera" -Name '(default)' -ErrorAction SilentlyContinue).'(default)' -eq $progId) {
            Remove-Item -Recurse -Force "$classes\.newera" -ErrorAction SilentlyContinue
        }
        Remove-ItemProperty -Path "$classes\.sh3d\OpenWithProgids" -Name $progId -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$classes\$progId", "$classes\Applications\newera-gui.exe" -ErrorAction SilentlyContinue
        Refresh-Shell
        Remove-FromUserPath $dir
        if (Get-Command claude -ErrorAction SilentlyContinue) {
            claude mcp remove --scope user newera 2>$null | Out-Null
        }
        if (Get-Command codex -ErrorAction SilentlyContinue) {
            codex mcp remove newera 2>$null | Out-Null
        }
        Info (T "removido: $dir, atalhos, associação .newera, PATH e o MCP 'newera' do Claude Code e do Codex" `
                 "removed: $dir, shortcuts, the .newera association, PATH and the 'newera' MCP from Claude Code and Codex" `
                 "eliminado: $dir, accesos directos, la asociación .newera, el PATH y el MCP 'newera' de Claude Code y Codex" `
                 "supprimés : $dir, les raccourcis, l'association .newera, le PATH et le MCP « newera » de Claude Code et Codex")
        return
    }

    Show-Logo

    Step (T 'Última versão' 'Latest version' 'Última versión' 'Dernière version')
    # github.com/<repo>/releases/latest redirects to the newest tag. Unlike the
    # REST API it has no per-IP limit, so offices behind one IP aren't blocked.
    $request = [Net.HttpWebRequest]::Create("https://github.com/$repo/releases/latest")
    $request.AllowAutoRedirect = $false
    $request.UserAgent = 'newera-installer'
    $response = $request.GetResponse()
    $location = $response.Headers['Location']
    $response.Close()
    if (-not $location -or $location -notmatch '/releases/tag/([^/?#]+)') {
        throw (T 'Nenhuma versão publicada ainda.' 'No release published yet.' `
                 'Ninguna versión publicada todavía.' "Aucune version publiée pour l'instant.")
    }
    $tag = [Uri]::UnescapeDataString($Matches[1])
    $assetName = 'newera-windows-x64.zip'
    Info $tag
    $versionFile = Join-Path $dir 'version.txt'
    if (-not $Force -and (Test-Path (Join-Path $dir 'newera-gui.exe')) -and
        (Test-Path $versionFile) -and ((Get-Content $versionFile -Raw).Trim() -eq $tag)) {
        Info (T 'já instalado nesta versão: nada a baixar (use -Force para reinstalar)' `
                  'already on this version: nothing to download (use -Force to reinstall)' `
                'ya instalado en esta versión: nada que descargar (use -Force para reinstalar)' `
                'déjà installé dans cette version : rien à télécharger (-Force réinstalle)')
    }
    else {
        $work = Join-Path ([IO.Path]::GetTempPath()) ("newera-install-" + [Guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $work | Out-Null
        try {
            Step "$(T 'Baixando' 'Downloading' 'Descargando' 'Téléchargement') $assetName"
            $zip = Join-Path $work 'newera.zip'
            try {
                Invoke-WebRequest "https://github.com/$repo/releases/download/$tag/$assetName" -OutFile $zip -UseBasicParsing
            }
            catch {
                throw (T "A versão $tag não tem o pacote para Windows ($assetName)." `
                         "Version $tag has no Windows package ($assetName)." `
                         "La versión $tag no tiene el paquete para Windows ($assetName)." `
                         "La version $tag n'a pas de paquet Windows ($assetName).")
            }
            Expand-Archive $zip -DestinationPath $work
            $unpacked = Join-Path $work $name
            & (Join-Path $unpacked 'newera.exe') --version | Out-Null
            if ($LASTEXITCODE -ne 0) {
                throw (T 'O programa baixado não abriu neste computador.' `
                         'The downloaded program did not run on this computer.' `
                         'El programa descargado no se abrió en este equipo.' `
                         "Le programme téléchargé n'a pas démarré sur cet ordinateur.")
            }

            Step "$(T 'Instalando em' 'Installing into' 'Instalando en' 'Installation dans') $dir"
            Remove-Item -Recurse -Force $dir -ErrorAction SilentlyContinue
            New-Item -ItemType Directory -Path (Split-Path $dir) -Force | Out-Null
            Move-Item $unpacked $dir
            Set-Content -Path $versionFile -Value $tag -Encoding ascii
            Info 'ok'
        }
        finally {
            Remove-Item -Recurse -Force $work -ErrorAction SilentlyContinue
        }
    }

    Step (T 'Atalhos' 'Shortcuts' 'Accesos directos' 'Raccourcis')
    $gui = Join-Path $dir 'newera-gui.exe'
    $shell = New-Object -ComObject WScript.Shell
    foreach ($link in @($startMenu, $desktop)) {
        $shortcut = $shell.CreateShortcut($link)
        $shortcut.TargetPath = $gui
        $shortcut.WorkingDirectory = [Environment]::GetFolderPath('MyDocuments')
        $shortcut.Description = 'Home design with a built-in MCP server'
        $shortcut.IconLocation = "$gui,0"
        $shortcut.Save()
    }
    Info (T 'Menu Iniciar e Área de Trabalho' 'Start menu and Desktop' `
             'Menú Inicio y Escritorio' 'Menu Démarrer et Bureau')

    Step (T 'Arquivos .newera' '.newera files' 'Archivos .newera' 'Fichiers .newera')
    # Per-user association: the projects get the document icon (the second icon
    # group inside newera-gui.exe) and open in the editor on a double click.
    $classes = 'HKCU:\Software\Classes'
    New-Item -Path "$classes\$progId\DefaultIcon" -Force | Out-Null
    New-Item -Path "$classes\$progId\shell\open\command" -Force | Out-Null
    Set-ItemProperty -Path "$classes\$progId" -Name '(default)' -Value '3D New Era AI project'
    Set-ItemProperty -Path "$classes\$progId\DefaultIcon" -Name '(default)' -Value "$gui,1"
    Set-ItemProperty -Path "$classes\$progId\shell\open\command" -Name '(default)' -Value "`"$gui`" `"%1`""
    New-Item -Path "$classes\.newera" -Force | Out-Null
    Set-ItemProperty -Path "$classes\.newera" -Name '(default)' -Value $progId
    Set-ItemProperty -Path "$classes\.newera" -Name 'Content Type' -Value 'application/x-newera'
    # Sweet Home 3D files: offered under "Open with", without taking the default.
    New-Item -Path "$classes\.sh3d\OpenWithProgids" -Force | Out-Null
    New-ItemProperty -Path "$classes\.sh3d\OpenWithProgids" -Name $progId -Value '' -PropertyType String -Force | Out-Null
    New-Item -Path "$classes\Applications\newera-gui.exe\shell\open\command" -Force | Out-Null
    Set-ItemProperty -Path "$classes\Applications\newera-gui.exe" -Name 'FriendlyAppName' -Value $name
    Set-ItemProperty -Path "$classes\Applications\newera-gui.exe\shell\open\command" -Name '(default)' -Value "`"$gui`" `"%1`""
    Refresh-Shell
    Info (T 'ícone e duplo clique para .newera' 'icon and double click for .newera' `
             'icono y doble clic para .newera' 'icône et double-clic pour .newera')

    Step (T 'Comando newera no PATH do usuário' 'The newera command on your PATH' `
             'Comando newera en el PATH del usuario' 'La commande newera dans votre PATH')
    $path = [Environment]::GetEnvironmentVariable('Path', 'User')
    if (-not (($path -split ';') | Where-Object { $_.TrimEnd('\') -eq $dir.TrimEnd('\') })) {
        [Environment]::SetEnvironmentVariable('Path', ((@($path, $dir) | Where-Object { $_ }) -join ';'), 'User')
        Info (T 'adicionado (abra um terminal novo)' 'added (open a new terminal)' `
                 'añadido (abra un terminal nuevo)' 'ajoutée (ouvrez un nouveau terminal)')
    }
    else { Info 'ok' }

    # Settings > Apps lists it, and its Uninstall button runs this same script.
    $uninstaller = Join-Path $dir 'uninstall.ps1'
    Set-Content -Path $uninstaller -Encoding utf8 -Value (
        "& ([scriptblock]::Create((Invoke-RestMethod 'https://raw.githubusercontent.com/$repo/main/scripts/install-windows.ps1'))) -Uninstall")
    New-Item -Path $uninstallKey -Force | Out-Null
    $version = $tag.TrimStart('v')
    @{
        DisplayName     = $name
        DisplayVersion  = $version
        Publisher       = '3D New Era AI'
        DisplayIcon     = $gui
        InstallLocation = $dir
        UninstallString = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$uninstaller`""
        URLInfoAbout    = "https://github.com/$repo"
    }.GetEnumerator() | ForEach-Object { New-ItemProperty -Path $uninstallKey -Name $_.Key -Value $_.Value -Force | Out-Null }
    New-ItemProperty -Path $uninstallKey -Name NoModify -Value 1 -PropertyType DWord -Force | Out-Null

    $mcpUrl = 'http://127.0.0.1:7878/mcp'
    if (Get-Command claude -ErrorAction SilentlyContinue) {
        Step (T 'MCP no Claude Code' 'MCP in Claude Code' 'MCP en Claude Code' 'MCP dans Claude Code')
        claude mcp get newera 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) { Info (T 'já registrado' 'already registered' 'ya registrado' 'déjà enregistré') }
        else {
            claude mcp add --scope user --transport http newera $mcpUrl 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) { Info (T "servidor 'newera' registrado" "'newera' server registered" `
                                           "servidor 'newera' registrado" "serveur « newera » enregistré") }
            else {
                $run = T 'não consegui registrar; rode' 'could not register; run' `
                         'no pude registrarlo; ejecute' "impossible de l'enregistrer ; lancez"
                Info "${run}: claude mcp add --transport http newera $mcpUrl"
            }
        }
    }
    if (Get-Command codex -ErrorAction SilentlyContinue) {
        Step (T 'MCP no Codex' 'MCP in Codex' 'MCP en Codex' 'MCP dans Codex')
        codex mcp get newera 2>$null | Out-Null
        if ($LASTEXITCODE -eq 0) { Info (T 'já registrado' 'already registered' 'ya registrado' 'déjà enregistré') }
        else {
            codex mcp add newera --url $mcpUrl 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) { Info (T "servidor 'newera' registrado" "'newera' server registered" `
                                           "servidor 'newera' registrado" "serveur « newera » enregistré") }
            else {
                $run = T 'não consegui registrar; rode' 'could not register; run' `
                         'no pude registrarlo; ejecute' "impossible de l'enregistrer ; lancez"
                Info "${run}: codex mcp add newera --url $mcpUrl"
            }
        }
    }

    Write-Host "`n$(T 'Pronto!' 'Done!' '¡Listo!' 'Terminé !')" -ForegroundColor Green
    switch ($script:Lang) {
        'pt' {
            Write-Host "  Abrir:        Menu Iniciar ou Área de Trabalho > $name"
            Write-Host '  Terminal:     newera --demo'
            Write-Host '  MCP:          http://127.0.0.1:7878/mcp (com o editor aberto; outras IAs: veja o README)'
            Write-Host '  Atualizar:    rode o mesmo comando de novo'
            Write-Host '  Desinstalar:  Configurações > Aplicativos > 3D New Era AI'
        }
        'es' {
            Write-Host "  Abrir:        Menú Inicio o Escritorio > $name"
            Write-Host '  Terminal:     newera --demo'
            Write-Host '  MCP:          http://127.0.0.1:7878/mcp (con el editor abierto; otras IA: vea el README)'
            Write-Host '  Actualizar:   ejecute el mismo comando otra vez'
            Write-Host '  Desinstalar:  Configuración > Aplicaciones > 3D New Era AI'
        }
        'fr' {
            Write-Host "  Ouvrir :      menu Démarrer ou Bureau > $name"
            Write-Host '  Terminal :    newera --demo'
            Write-Host "  MCP :         http://127.0.0.1:7878/mcp (avec l'éditeur ouvert ; autres IA : voir le README)"
            Write-Host '  Mettre à jour : relancez la même commande'
            Write-Host '  Désinstaller : Paramètres > Applications > 3D New Era AI'
        }
        default {
            Write-Host "  Open:         Start menu or Desktop > $name"
            Write-Host '  Terminal:     newera --demo'
            Write-Host '  MCP:          http://127.0.0.1:7878/mcp (with the editor open; other AIs: see the README)'
            Write-Host '  Update:       run the same command again'
            Write-Host '  Uninstall:    Settings > Apps > 3D New Era AI'
        }
    }
}

Install-NewEra -Uninstall:$Uninstall -Force:$Force
