#!/usr/bin/env bash
# Builds the public site into _site/: the landing page at the root, the full
# editor at /app/ and the lightweight viewer at /viewer/, with the showcase
# images the pages reference.
#
#   scripts/site-build.sh            # expects web/ already built
#   BUILD_WASM=1 scripts/site-build.sh   # builds the WebAssembly first
#
# The editor and the viewer are static: they run in the visitor's tab and
# talk to no server of ours.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
out="${1:-_site}"

if [ "${BUILD_WASM:-0}" = "1" ]; then
  make web web-editor
fi

for needed in web/newera_web.wasm web/editor/pkg/newera_editor_web_bg.wasm; do
  [ -f "$needed" ] || {
    echo "missing $needed — run 'make web web-editor' (or BUILD_WASM=1)" >&2
    exit 1
  }
done

rm -rf "$out"
mkdir -p "$out/images" "$out/app" "$out/viewer"

# The landing page and everything beside it.
cp -r site/. "$out/"

# Showcase images live in docs/ so the README can use them too.
cp -r docs/images/showcase "$out/images/"
cp docs/images/editor.png "$out/images/"

# The editor: the page, the glue and the wasm, plus the home it opens on.
cp web/editor/index.html "$out/app/"
mkdir -p "$out/app/pkg"
cp web/editor/pkg/newera_editor_web.js web/editor/pkg/newera_editor_web_bg.wasm "$out/app/pkg/"
cp web/demo.newera "$out/demo.newera"

# The viewer, which opens a project without the editor.
cp web/index.html web/viewer.js web/newera_web.wasm "$out/viewer/"
cp site/favicon.svg "$out/viewer/favicon.svg"

# Nothing here is generated by Jekyll.
touch "$out/.nojekyll"

printf 'built %s (%s)\n' "$out" "$(du -sh "$out" | cut -f1)"
