#!/usr/bin/env bash
# Builds the public site into _site/: the landing page at the root, the full
# editor at /app/ and the lightweight viewer at /viewer/, with the showcase
# images the pages reference.
#
#   scripts/site-build.sh            # expects web/ already built
#   BUILD_WASM=1 scripts/site-build.sh   # builds the WebAssembly first
#
# The editor and the viewer are static: they run in the visitor's tab and
# talk to no server of ours.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"
out="${1:-_site}"

if [ "${BUILD_WASM:-0}" = "1" ]; then
  make web web-editor
fi

for needed in web/newera_web.wasm web/editor/pkg/newera_editor_web_bg.wasm; do
  [ -f "$needed" ] || {
    echo "missing $needed — run 'make web web-editor' (or BUILD_WASM=1)" >&2
    exit 1
  }
done

rm -rf "$out"
mkdir -p "$out/images" "$out/app" "$out/viewer"

# The landing page and everything beside it.
cp -r site/. "$out/"

# Showcase images live in docs/ so the README can use them too.
cp -r docs/images/showcase "$out/images/"
cp docs/images/editor.png "$out/images/"

# The editor: the page, the glue and the wasm, plus the home it opens on.
#
# The glue and the wasm keep their names across releases, and a browser caches
# them apart — one old half plus one new half does not link. Each build stamps
# both URLs with the digest of its own wasm, so a cache can only serve a pair
# that belongs together.
stamp() { shasum -a 256 "$1" | cut -c1-12; }
editor_build="$(stamp web/editor/pkg/newera_editor_web_bg.wasm)"
sed "s/__BUILD__/$editor_build/g" web/editor/index.html > "$out/app/index.html"
mkdir -p "$out/app/pkg"
cp web/editor/pkg/newera_editor_web.js web/editor/pkg/newera_editor_web_bg.wasm "$out/app/pkg/"
cp web/demo.newera "$out/demo.newera"

# The viewer, which opens a project without the editor. Same reasoning.
viewer_build="$(stamp web/newera_web.wasm)"
sed "s/__BUILD__/$viewer_build/g" web/index.html > "$out/viewer/index.html"
cp web/viewer.js web/newera_web.wasm "$out/viewer/"
cp site/favicon.svg "$out/viewer/favicon.svg"

# Nothing here is generated by Jekyll.
touch "$out/.nojekyll"

printf 'built %s (%s)\n' "$out" "$(du -sh "$out" | cut -f1)"
